"""empty message

Revision ID: 0993fa4746d1
Revises: b8eaf49b0eda
Create Date: 2022-08-10 14:41:29.551383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0993fa4746d1'
down_revision = 'b8eaf49b0eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disable')
    # ### end Alembic commands ###
