"""empty message

Revision ID: 0e707a3de53b
Revises: 93a4fe22437b
Create Date: 2022-07-27 14:48:05.330386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e707a3de53b'
down_revision = '93a4fe22437b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', mysql.TEXT(), nullable=True))
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
