"""empty message

Revision ID: 806df69c92ca
Revises: c127f0d34656
Create Date: 2022-07-16 16:35:10.375910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806df69c92ca'
down_revision = 'c127f0d34656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'avatar_hash')
    # ### end Alembic commands ###
