"""empty message

Revision ID: c127f0d34656
Revises: 
Create Date: 2022-07-10 20:20:46.838370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c127f0d34656'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('student_id', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('member_added_year', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('member_id', sa.Integer(), nullable=True))
    op.drop_column('clients', 'class_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('class_id', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('clients', 'member_id')
    op.drop_column('clients', 'member_added_year')
    op.drop_column('clients', 'student_id')
    # ### end Alembic commands ###
