"""empty message

Revision ID: c5b8eec60463
Revises: 0e707a3de53b
Create Date: 2022-07-27 15:17:35.273786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b8eec60463'
down_revision = '0e707a3de53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###
